CHARACTER_MATCH = {
        "Twilight Sparkle": "Twilight Sparkle",
        "Fluttershy": "Fluttershy",
        "Rarity": "Rarity",
        "Applejack": "Applejack",
        "Rainbow Dash": "Rainbow Dash",
        "Pinkie Pie": "Pinkie Pie",
        "Princess Celestia": "Princess Celestia",
        "Princess Luna": "Princess Luna",
        "Spike": "Spike",
        "Starlight Glimmer": "Starlight Glimmer",
        "Trixie": "Trixie",
        "Apple Bloom": "Apple Bloom",
        "Sweetie Belle": "Sweetie Belle",
        "Scootaloo": "Scootaloo",
        "Zecora": "Zecora",
        "Derpy Hooves": "Derpy Hooves",
        "Lyra": "Lyra",
        "Bon Bon": "Bon Bon",
        "Princess Cadance": "Princess Cadance",
        "Cozy Glow": "Cozy Glow",
        "Queen Chrysalis": "Queen Chrysalis",
        "Spitfire": "Spitfire",
        "Big Mac": "Big Mac",
        "Sunburst": "Sunburst",
        "Minuette": "Minuette",
        "Cheerilee": "Cheerilee",
        "Coco Pommel": "Coco Pommel",
        "Maud Pie": "Maud Pie",
        "Shining Armor": "Shining Armor",
        "Sugar Belle": "Sugar Belle",
        "Vapor Trail": "Vapor Trail",
        "Moondancer": "Moondancer",
        "Lightning Dust": "Lightning Dust",
        "Discord": "Discord",
        "Soarin'": "Soarin'",
        "Diamond Tiara": "Diamond Tiara",
        "Silver Spoon": "Silver Spoon",
        "Octavia": "Octavia",
        "Gilda": "Gilda",
        "Gabby": "Gabby",
        "Limestone Pie": "Limestone Pie",
        "Braeburn": "Braeburn",
        "Daring Do": "Daring Do",
        "Snips": "Snips",
        "Snails": "Snails",
        "Sunset Shimmer": "Sunset Shimmer",
        "Adagio Dazzle": "Adagio Dazzle",
        "Aria Blaze": "Aria Blaze",
        "Sonata Dusk": "Sonata Dusk",
        "HAL 9000": "HAL 9000",
        "GLaDOS": "GLaDOS",
        "Wheatley": "Wheatley",
        "Sentry Turret": "Sentry Turret",
        "Miss Pauling": "Miss Pauling",
        "Scout": "Scout",
        "Soldier": "Soldier",
        "Demoman": "Demoman",
        "Heavy": "Heavy",
        "Engineer": "Engineer",
        "Medic": "Medic",
        "Sniper": "Sniper",
        "Spy": "Spy",
        "Rise Kujikawa": "Rise Kujikawa",
        "SpongeBob SquarePants": "SpongeBob SquarePants",
        "Announcer": "Announcer",
        "Steven Universe": "Steven Universe",
        "The Narrator": "The Narrator",
        "Stanley": "Stanley",
        "Yes Man": "Yes Man",
        "Carl Brutananadilewski": "Carl Brutananadilewski",
        "Dan": "Dan",
        "Daria Morgendorffer": "Daria Morgendorffer",
        "Jane Lane": "Jane Lane",
        "Black Mesa Announcer": "Black Mesa Announcer",
        "Overwatch": "Overwatch",
        "Kyu Sugardust": "Kyu Sugardust",
        "Tenth Doctor": "Tenth Doctor",
        "dt": "Diamond Tiara",
        "ss": "Silver Spoon",
        "ab": "Apple Bloom",
        "luna": "Princess Luna",
        "pcd": "Princess Cadance",
        "sa": "Shining Armor",
        "sb": "Sweetie Belle",
        "sg": "Starlight Glimmer",
        "aj": "Applejack",
        "fs": "Fluttershy",
        "pp": "Pinkie Pie",
        "rd": "Rainbow Dash",
        "ry": "Rarity",
        "sp": "Spike",
        "ts": "Twilight Sparkle",
        "bb": "Braeburn",
        "bm": "Big Macintosh",
        "dc": "Discord",
        "ld": "Lightning Dust",
        "qc": "Queen Chrysalis",
        "sf": "Spitfire",
        "sn": "Soarin'",
        "sus": "Sunset Shimmer",
        "tx": "Trixie",
}

def match_character(s):
    return CHARACTER_MATCH.get(s)
